### PR TITLE
Add dispatch argument to middleware functions

### PR DESCRIPTION
**Pull request by claytn**
* This pr is still a work in progress. 
I began tinkering with ways to give the user access to dispatch directly and I found a way to do it. However, when running the todo_example I'm getting an error I can't quite figure out. I'm getting a BorrowMutError inside of the Store dispatch function. I never store a mutable borrow of the State's RefCell, but this error continues to appear. I found that the nightly compiler(which is what I've been using) has had errors in the past where it doesn't correctly detect mutable borrows of a RefCell. I tried switching to the stable rust compiler and I still got the same error. I am going to do some more digging, but I'd like to get your take as well on it. Is there something obvious I'm missing here?

### CODE REVIEW

**Comment by fanderzon** [comment]
If there is an active borrow (mutable or immutable) you're not allowed to call `borrow_mut` on a RefCell I think, so the (quick) solution is to clone the state when passing it to middleware and listeners.

And to avoid code duplication you could just use `&self.get_state()` (which already does a borrow and a clone of the state) whenever you want to pass on the state.

I'm perfectly happy if we first make this work the way we want it to, and we can look at performance optimizations and thread safety and other fun things later.

**Comment by claytn** [comment]
I was able to fix the error with what you recommended, but I'm not sure I understand why it wasn't working before.
Here is the code that was failing before.
```
let updated_state = (self.reducer)(&self.state.borrow().inner_state, &action);
        self.state.borrow_mut().inner_state = updated_state;

        for middleware in &self.middlewares{
            middleware(&self.state.borrow().inner_state, &|action:U|{
                self.dispatch(action);
            }, &action);
        }

        for listener in &self.listeners {
            listener(&self.state.borrow().inner_state)
        }
```
At no point do I store a reference to the borrow_mut() so I don't understand why I am not allowed to borrow() the state after the updated state line. Do you have any further explanation on why this doesn't work?

**Comment by fanderzon** [comment]
Well, the way I pictured the flow was that for each action dispatch would run once, mutably borrowing the state and updating it and then it would start looping through the middleware, borrowing the state and passing it to each middleware.

And then your middleware called dispatch which would try to mutably borrow the state, but the middleware was still borrowing the state immutably so the RefCell would panic.

**Review by fanderzon — APPROVED** [review]

**Comment by claytn** [comment]
Ahhh... the problem isn't between the first borrow_mut() and the borrow(). It's the fact that you borrow() and then within that inner called dispatch you call borrow_mut().

**Pull request merged**
